
<div id="footer">
    <div id="footer-content">
        <a id="logo-footer" href="<?=URL_AVALIE?>"><div id="logo-footer"></div></a>
        <div id="footer-links">
            <a href="">Contato</a> | 
            <a href="<?= URL_AVALIE ?>page/quemsomos">Quem Somos</a> |
            <a href="">Cadastre-se</a>                </div>
        <div id="social">
            <a href=""><img src="<?= URL_IMAGES ?>bt_fb.png"></a> 
            <a href=""><img src="<?= URL_IMAGES ?>bt_tw.png"></a> 
            <a href=""><img src="<?= URL_IMAGES ?>bt_yt.png"></a>                </div>
    </div>


</div>
</div>
</body>
</html>
