<?php $ArMessage = Message::getMessage(); ?>
<script>
    $('document').ready(function() {
        avaliar.setEvents();
    });
</script>
<div id="main-content">
    <div id="instituicao-perfil">
        <?php $BlLogoIn64 = base64_encode($_Instituicao->getBlLogo()); ?>
        <div id="logo-container">
            <img id="logo-instituicao" src="data:image/png;base64,<?= $BlLogoIn64 ?>"/>
        </div>
        <div id="dados-basicos">
            <?php echo $_Instituicao->getStNome(); ?>
        </div>
    </div>
    <?php if ($ArMessage): ?>
        <div class="<?= !$ArMessage['StType'] ? 'erro' : 'sucesso' ?>">
            <?= $ArMessage['StMessage'] ?>
        </div>
    <?php endif; ?>
    <form id="avaliacao" method="post" action="<?= URL_AVALIE ?>avaliacao/avaliarSubmit/">
        <div id="box-avaliacao">
            <?php foreach ($_ArQuestoesPorConceitos as $StConceito => $Questoes): ?>
                <div class="conceito-box">
                    <div class="conceito-titulo">
                        <?= $StConceito; ?>
                    </div>
                    <?php foreach ($Questoes as $Questao): ?>
                        <div class="avaliacao-questao">
                            <div class="questao-texto"><?= $Questao->getStQuestao(); ?>
                                <ol class="stars">
                                    <li></li><li></li><li></li><li></li><li></li>
                                </ol>
                                <input type="hidden" name="ArAvaliacao[<?= $Questao->getIDQuestao(); ?>]" value="">
                            </div>                            
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        </div>

        <input type="hidden" name="IDInstituicao" value="<?= $_Instituicao->getIDInstituicao(); ?>">
        <input type="submit" class="button link-button-verde" style="margin-top: 30px;">
    </form>
    <div id="sql"></div>
    <div class="clear"></div>
</div>
