<?php
$ArMessage = Message::getMessage();
if ($ArMessage) {
    if ($ArMessage['StType'] === 'aviso') {
        $StMsgClass = 'aviso';
    } else {
        $StMsgClass = !$ArMessage['StType'] ? 'erro' : 'sucesso';
    }
}
?>
<div id="main-content">
    <ul id='lista-instituicoes'>
        <?php $i = 1; ?>
        <?php foreach ($_ArInstituicoes as $Instituicao): ?>
            <li>
                <div class="colocacao"><?= $i ?></div>
                <div style="float: left; margin-top: 17px;margin-left: 30px;">
                    <div style="font-size: 20px;"><a href="<?= URL_AVALIE ?>instituicao/perfil/id/<?= $Instituicao->getIDInstituicao(); ?>"><?php echo $Instituicao->getStNome(); ?></a>
                        <?php $BlLogoIn64 = base64_encode($Instituicao->getBlLogo()); ?>
                    </div>
                    <div class="instituicao-media-listagem">
                        Média <?= $Instituicao->getFlMediaGeral() ?>
                    </div>
                </div>

                <div class="logo-instituicao">
                    <img id="logo-instituicao" src="data:image/png;base64,<?= $BlLogoIn64 ?>"/>
                </div>
            </li>
            <?php $i++; ?>
        <?php endforeach; ?>
    </ul>
    <div class="clear"></div>
</div>